### ISSUE TITLE
Negative closing balances 

### ISSUE THREAD

**Issue by NaasvanH** [TheProfitTable/loanportr#19]
Take out negative closing balances: `pd` function

**Comment by NaasvanH** [comment]
Don't think this is necessary anymore? There might have been an issue on the graph that was sorted out in some other way. Can't recall? @DandeVilliers do you perhaps remember?

**Comment by DandeVilliers** [comment]
There is an issue on the Onbook Sales plot if segmented by Disclosure and weighted by Net, there are large values for `NPL-WrittenOff` for Jan through March 2017. Not sure if that is related.

**Comment by NaasvanH** [comment]
No not related. I think that is most likely a client side data issue.
